[package]
name = "pkg"
version = "0.1.0"
authors = ["coderstephen <me@stephencoakley.com>"]

[lib]
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
flate2 = "0.2"
script = { path = "../script" }
tar = "0.3.2"
time = "0.1"
